name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: 49ad95b5c22e4d8778a4c8f12be673a0
          TIMEZONE: Asia/Seoul
